  version: '3.8'

  services:
    identity-db:
      image: postgres:16
      container_name: identity-db
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: identitydb
      volumes:
        - identity-db-data:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"
      networks:
        - marketHub-net

  volumes:
    identity-db-data:

  networks:
    marketHub-net:
      driver: bridge