  version: '3.8'
  services:

    mssql-db:
      image: mcr.microsoft.com/mssql/server:2019-CU19-ubuntu-20.04
      container_name: mssql-db  # Add this line
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=YourStrong@Passw0rd
        - MSSQL_PID=Enterprise
      ports:
        - "1433:1433"
      volumes:
        - mssql-db-data:/var/opt/mssql
      networks:
        - mssql-network
      healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 5


    postgres-db:
      image: postgres:16
      container_name: postgres-db
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
      volumes:
        - postgres-db-data:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"
      networks:
        - postgres-net


    mongo-db:
      image: mongo:latest
      container_name: mongo-db
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: examplepassword
      volumes:
        - mongo-db-data:/data/db
      networks:
        - mongo-network

    mongo-express:
      image: mongo-express:latest
      container_name: mongo-express
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: examplepassword
        ME_CONFIG_MONGODB_SERVER: mongo-db
        ME_CONFIG_BASICAUTH_USERNAME: "sa"   # Disables basic auth prompt
        ME_CONFIG_BASICAUTH_PASSWORD: "12345678"
      depends_on:
        - mongo-db
      networks:
      - mongo-network

    elasticsearch:
      container_name: elastic-search
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
      networks:
        - elk-network

    logstash:
      container_name: logstash
      image: docker.elastic.co/logstash/logstash:7.17.0
      ports:
        - "5044:5044"
        - "9600:9600"
      volumes:
        - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      networks:
        - elk-network

    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.15.0
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://elastic-search:9200  # Fixed the hostname
      depends_on:
        - elasticsearch
      networks:
        - elk-network

    rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.13-management
    
      ports:
        - "5672:5672"  # AMQP protocol port
        - "15672:15672"  # Management UI port
      environment:
        - RABBITMQ_DEFAULT_USER=Sa
        - RABBITMQ_DEFAULT_PASS=#54987jshd&%4
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq  
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro  
      healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 30s
        timeout: 10s
        retries: 3
      networks:
        - rabbitmq_net

  volumes:
    postgres-db-data:
    mongo-db-data:
    elasticsearch-data:
    mssql-db-data:
    rabbitmq_data:

  networks:
    postgres-net:
      driver: bridge
    mongo-network:
      driver: bridge
    elk-network:
      driver: bridge
    mssql-network:
      driver: bridge
    rabbitmq_net:
      driver: bridge
    